// const teams2324 = {
//   epl: {
//     arsenal: {
//       key: 1,
//       value: 'Arsenal',
//       fullTeamNameRU: 'Арсенал',
//       shortTeamNameRU: 'АРС',
//       fullTeamNameEN: 'Arsenal',
//       shortTeamNameEN: 'ARS',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/arsenal.png`,
//     },
//     aston_villa: {
//       key: 2,
//       value: 'Aston Villa',
//       fullTeamNameRU: 'Астон Вилла',
//       shortTeamNameRU: 'АСТ',
//       fullTeamNameEN: 'Aston Villa',
//       shortTeamNameEN: 'AVI',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/aston_villa.png`,
//     },
//     burnley: {
//       key: 3,
//       value: 'Burnley',
//       fullTeamNameRU: 'Бернли',
//       shortTeamNameRU: 'БЕР',
//       fullTeamNameEN: 'Burnley',
//       shortTeamNameEN: 'BUR',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/burnley.png`,
//     },
//     bournemouth: {
//       key: 4,
//       value: 'Bournemouth',
//       fullTeamNameRU: 'Борнмут',
//       shortTeamNameRU: 'БОР',
//       fullTeamNameEN: 'Bournemouth',
//       shortTeamNameEN: 'BOU',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/bournemouth.png`,
//     },
//     brighton: {
//       key: 5,
//       value: 'Brighton',
//       fullTeamNameRU: 'Брайтон',
//       shortTeamNameRU: 'БРА',
//       fullTeamNameEN: 'Brighton',
//       shortTeamNameEN: 'BRI',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/brighton.png`,
//     },
//     brentford: {
//       key: 6,
//       value: 'Brentford',
//       fullTeamNameRU: 'Брентфорд',
//       shortTeamNameRU: 'БРЕ',
//       fullTeamNameEN: 'Brentford',
//       shortTeamNameEN: 'BRE',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/brentford.png`,
//     },
//     west_ham: {
//       key: 7,
//       value: 'West Ham',
//       fullTeamNameRU: 'Вест Хэм',
//       shortTeamNameRU: 'ВСХ',
//       fullTeamNameEN: 'West Ham',
//       shortTeamNameEN: 'WHU',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/west_ham.png`,
//     },
//     wolverhampton: {
//       key: 8,
//       value: 'Wolverhampton',
//       fullTeamNameRU: 'Вулверхэмптон',
//       shortTeamNameRU: 'ВУЛ',
//       fullTeamNameEN: 'Wolverhampton',
//       shortTeamNameEN: 'WOL',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/wolverhampton.png`,
//     },
//     crystal_palace: {
//       key: 9,
//       value: 'Crystal Palace',
//       fullTeamNameRU: 'Кристал Пэлас',
//       shortTeamNameRU: 'КРП',
//       fullTeamNameEN: 'Crystal Palace',
//       shortTeamNameEN: 'CRP',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/crystal_palace.png`,
//     },
//     liverpool: {
//       key: 10,
//       value: 'Liverpool',
//       fullTeamNameRU: 'Ливерпуль',
//       shortTeamNameRU: 'ЛИВ',
//       fullTeamNameEN: 'Liverpool',
//       shortTeamNameEN: 'LIV',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/liverpool.png`,
//     },
//     luton: {
//       key: 11,
//       value: 'Luton Town',
//       fullTeamNameRU: 'Лутон',
//       shortTeamNameRU: 'ЛУТ',
//       fullTeamNameEN: 'Luton',
//       shortTeamNameEN: 'LUT',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/luton.png`,
//     },
//     man_city: {
//       key: 12,
//       value: 'Manchester City',
//       fullTeamNameRU: 'Манчестер Сити',
//       shortTeamNameRU: 'МС',
//       fullTeamNameEN: 'Manchester City',
//       shortTeamNameEN: 'MC',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/man_city.png`,
//     },
//     man_united: {
//       key: 13,
//       value: 'Manchester United',
//       fullTeamNameRU: 'Манчестер Юнайтед',
//       shortTeamNameRU: 'МЮ',
//       fullTeamNameEN: 'Manchester United',
//       shortTeamNameEN: 'MU',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/man_united.png`,
//     },
//     nottingham_forest: {
//       key: 14,
//       value: 'Nottingham Forest',
//       fullTeamNameRU: 'Ноттингем',
//       shortTeamNameRU: 'НОТ',
//       fullTeamNameEN: 'Nottingham',
//       shortTeamNameEN: 'NFO',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/nottingham_forest.png`,
//     },
//     newcastle: {
//       key: 15,
//       value: 'Newcastle',
//       fullTeamNameRU: 'Ньюкасл',
//       shortTeamNameRU: 'НЬЮ',
//       fullTeamNameEN: 'Newcastle',
//       shortTeamNameEN: 'NEW',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/newcastle.png`,
//     },
//     tottenham: {
//       key: 16,
//       value: 'Tottenham',
//       fullTeamNameRU: 'Тоттенхэм',
//       shortTeamNameRU: 'ТТХ',
//       fullTeamNameEN: 'Tottenham',
//       shortTeamNameEN: 'TOT',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/tottenham.png`,
//     },
//     fulham: {
//       key: 17,
//       value: 'Fulham',
//       fullTeamNameRU: 'Фулхэм',
//       shortTeamNameRU: 'ФУЛ',
//       fullTeamNameEN: 'Fulham',
//       shortTeamNameEN: 'FUL',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/fulham.png`,
//     },
//     chelsea: {
//       key: 18,
//       value: 'Chelsea',
//       fullTeamNameRU: 'Челси',
//       shortTeamNameRU: 'ЧЕЛ',
//       fullTeamNameEN: 'Chelsea',
//       shortTeamNameEN: 'CHE',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/chelsea.png`,
//     },
//     sheffield_united: {
//       key: 19,
//       value: 'Sheffield United',
//       fullTeamNameRU: 'Шеффилд',
//       shortTeamNameRU: 'ШЕФ',
//       fullTeamNameEN: 'Sheffield United',
//       shortTeamNameEN: 'SHU',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/sheffield_united.png`,
//     },
//     everton: {
//       key: 20,
//       value: 'Everton',
//       fullTeamNameRU: 'Эвертон',
//       shortTeamNameRU: 'ЭВЕ',
//       fullTeamNameEN: 'Everton',
//       shortTeamNameEN: 'EVE',
//       country: 'ENG',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/everton.png`,
//     },
//   },
//   bundesliga: {
//     bayern_munich: {
//       key: 21,
//       text: 'MUN',
//       value: 'Bayern Munich',
//       fullTeamNameRU: 'Бавария',
//       shortTeamNameRU: 'БАВ',
//       fullTeamNameEN: 'Bayern',
//       shortTeamNameEN: 'MUN',
//       country: 'GER',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/bayern_munich.png`,
//     },
//     bvb: {
//       key: 22,
//       text: 'BVB',
//       value: 'Borussia Dortmund',
//       fullTeamNameRU: 'Боруссия Д',
//       shortTeamNameRU: 'ДОР',
//       fullTeamNameEN: 'Dortmund',
//       shortTeamNameEN: 'BVB',
//       country: 'GER',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/bvb.png`,
//     },
//     rb_leipzig: {
//       key: 23,
//       value: 'RB Leipzig',
//       text: 'RBL',
//       fullTeamNameRU: 'РБ Лейпциг',
//       shortTeamNameRU: 'ЛЕЙ',
//       fullTeamNameEN: 'RB Leipzig',
//       shortTeamNameEN: 'RBL',
//       country: 'GER',
//       logo: `${process.env.PUBLIC_URL}/teams_logo/rb_leipzig.png`,
//     },
//   },
//   ucl: {},
// };

const friendOptions = [
  {
    key: 'Borussia Dortmund',
    text: 'Боруссия Д',
    value: 'BVB',
    image: `${process.env.PUBLIC_URL}/teams_logo/bvb.png`,
  },
  {
    key: 'Bayern Munich',
    text: 'Бавария',
    value: 'MUN',
    image: {
      avatar: true,
      src: `${process.env.PUBLIC_URL}/teams_logo/bayern_munich.png`,
    },
  },
  {
    key: 'RB Leipzig',
    text: 'РБ Лейпциг',
    value: 'RBL',
    image: {
      avatar: true,
      src: `${process.env.PUBLIC_URL}/teams_logo/rb_leipzig.png`,
    },
  },
];

export default friendOptions;
